# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

default_language_version:
  python: python3.12

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: pixi run ruff check --fix --force-exclude --config=pyproject.toml
        language: system
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        name: ruff format
        entry: pixi run ruff format --force-exclude --config=pyproject.toml
        language: system
        types_or: [python, pyi, jupyter]
      - id: submodule-check
        name: "WARNING: You are about to update the version of submodule cosmos-xenna, Are you sure? - y/N: "
        entry: .githooks/submodule-check.sh
        language: script
        types: [shell]
