[pytest]
pythonpath = .
testpaths = tests
addopts = --import-mode=importlib --disable-warnings -m 'not env' -p tests.utils.gpu_worker_limiter
markers =
    env(name): requires specific Pixi environment
asyncio_default_fixture_loop_scope = function
